services:

  golang:
    build: golang
    command: >
      sh -c './binary && sleep infinity'
    volumes:
      - ./mounted-config.toml:/app/config-override.toml
    environment:
      APP_SERVER_JWT_SECRET: ${JWT_SECRET?Provide a JWT_SECRET}
      APP_DATABASE_PASSWORD: ${DATABASE_PASSWORD?Provide a DATABASE_PASSWORD}